apiVersion: v1
kind: Service
metadata:
  name: namegen
  namespace: namegen
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb

  selector:
    app: namegen

  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP